# Generated by Django 5.0.6 on 2024-07-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of publisher', max_length=20)),
                ('website', models.URLField(help_text="Publisher's website")),
                ('email', models.EmailField(help_text='publishers email', max_length=254)),
            ],
        ),
    ]
